# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: foochane
subtitle: foochane
description: 心若浮沉，浅笑安然。
keywords: foochane
author: foochane
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: https://foochane.github.io
url: https://foochane.cn/
root: /
# permalink: :year/:month/:day/:title/
# permalink_defaults:
permalink: article/:urlname.html # 文章永久链接 urlname值文章里必须填写，格式201905260105
permalink_defaults: 
  urlname: unnamed

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# 新增
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html
# deploy:
#   type: git
#   repo: https://github.com/foochane/foochane.github.io.git
# deploy:
#   type: git
#   repo:
#       github: git@github.com/foochane/foochane.github.io.git,master
#       coding: git@git.dev.tencent.com/foochane/foochane-hexo.git,master
deploy:
- type: git
  repo: git@github.com:foochane/foochane.github.io.git
  branch: master
- type: git
  repo: git@git.dev.tencent.com:foochane/foochane.git
  branch: master
- type: git 
  repo: git@gitee.com:foochane/foochane.git
  branch: master

# 主题中还使用到了 hexo-generator-search 的 Hexo 插件来做内容搜索
search:
  path: search.xml
  field: post

#用 hexo-permalink-pinyin Hexo 插件使在生成文章时生成中文拼音的永久链接
# permalink_pinyin:
#   enable: ture
#   separator: '-' # default: '-'


# 文章字数统计插件 hexo-wordcount
wordCount:
  enable: false # 将这个值设置为 true 即可.
  postWordCount: true
  min2read: true
  totalCount: true

# 添加 RSS 订阅支持,主题中还使用到了 hexo-generator-feed 的 Hexo 插件来做 RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date


# 博文压缩hexo-neat
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/matery.js' 
    - '**/clicklove.js'